### PR TITLE
hold using trigger option

### PR DESCRIPTION
**Pull request by wilg**

### CODE REVIEW

**Comment by keithbradner** [comment]
I'd rather not add this. The way I'd rather people do this is just change the value of HoldButton to the trigger.

**Comment by wilg** [comment]
That approach makes it hard to do the clean updates as suggested in the readme:

> I recommend you clone the repo locally and create a symbolic link to your project so you can get updates and merge changes cleanly.

**Comment by wilg** [comment]
And `HoldButton` is private so its a bit wonky to try and subclass `NVRHand`. Plus, then you'd have to make your own controller prefab which would also make clean updating a bit weird.

**Comment by RenStrike** [comment]
Agreed.  I've really wanted a way to easily switch it to the trigger without having to do a weird workaround.

I LOVE this prefab though. Thanks for making it!  Was very easy to set up.

**Comment by keithbradner** [comment]
How about we make the variable serialized, then you can set it on the prefab to whatever you want?

**Comment by RenStrike** [comment]
I think that works for me.  That'd be great!

**Comment by wilg** [comment]
That sounds perfect!

**Pull request closed without merging**
