### PR TITLE
Moved button state to getters with cached values

### PR DESCRIPTION
**Pull request by jbroadway**
Lazy loading the button states reduces the number of states we read each update and only reads them when accessed individually. Also memoizes the result for the remainder of the frame. I was seeing NVRHand.Update() taking up to 2.5ms in the profiler, so this should help speed things up a bit :)

### CODE REVIEW

**Comment by jbroadway** [comment]
I also needed events on the hands themselves, so I added that here too.

**Comment by jbroadway** [comment]
I just merged the latest changes you guys made since 1.12 to fix the merge conflict with this pull request.

**Comment by jbroadway** [comment]
I have just merged your latest changes again. Any chance someone can look at this soon?

Maybe it'll help if I explain my thinking more. When I was profiling our app that uses NewtonVR, I noticed `NVRHand.Update()` was consistently eating up around 2.5ms of time per frame just reading all the button states. That is a lot of time when you're trying to keep the total frame under 11ms.

My solution doesn't change the surface API usage in any way, and shouldn't add any noticeable overhead, but assumes that not every button state is going to be checked by developers every frame, so only the ones that are needed get checked when they're actually requested, then cached for the duration of the frame. This has led to a big speedup for us, and I think will help noticeably improve performance for most use cases.

Thanks and happy new year!

**Comment by keithbradner** [comment]
Hi jbroadway, first of all, thanks for the push!

I've been doing profiling on newtonvr in 5.5 patch 3 and am only seeing nvrhand.update taking 0.03ms per frame. Are you on a really old version of unity or something? Not sure where this discrepancy is coming from

**Comment by jbroadway** [comment]
I'm on 5.4.3p3, but I was on 5.4.3p1 when I originally submitted the PR. Some assets are not working in 5.5 yet, so that has us holding back on upgrading. We're testing on both HTC Vive and Oculus Touch, but I'll have to test again tomorrow to see if the issue is more present on one than the other.

Even if the speed has been improved in 5.5 (for both Vive and Touch), I think 5.4 is going to be used by some developers for a while yet, and I think these improvements are still useful in both cases:

- Lazy loading so inputs are only checked when requested, instead of every button on both hands for every frame.
- Memoized results, which means the underlying SDK doesn't need to be called again when the user requests the same inputs twice in a single frame (i.e., if someone has multiple input controllers for different contexts, no need to re-check if a button was down for that frame because we already know it will be true).
- Two new Unity events on NVRHand: OnBeginInteraction and OnEndInteraction, so events can be tied to the hands and not just to NVRInteractable objects.

**Comment by keithbradner** [comment]
Sorry I'm being pretty picky (and slow) on the push requests I'm accepting. This looks pretty solid though. I kind of prefer calling the underlying sdk whenever the user is asking for the current button state, just in case they're doing something weird, but I definitely see the value of the lazy loading too and am going to prefer the likely performant solution here. I'm going to merge this into main. Thanks again for updating your request so there are no conflicts!

**Pull request merged**
