### PR TITLE
Windows Mixed Reality support (experimental)

### PR DESCRIPTION
**Pull request by etiennemargraff**
## Notes about Mixed Reality support (Experimental)

[@Jesseric](https://twitter.com/jerressic) and I ([@meulta](https://twitter.com/meulta)) added the support for [Windows Mixed Reality](https://developer.microsoft.com/en-us/windows/mixed-reality). 

Steps to use it:
- You don't have to change anything and your newtonVR code should work on Mixed Reality headsets and controllers. 
- For now MR only works with the MRTP version of Unity (grab the latest which is 5 today [here](http://beta.unity3d.com/download/a07ad30bae31/download.html))
- Add the Mixed Reality Toolkit to your project as an asset. You can clone it from here: https://github.com/Microsoft/MixedRealityToolkit
- One MRTK is added to the project, open the **Mixed Reality Toolkit** menu and go in **Configure > Apply Mixed Reality Project** Settings. Check **Target Occluded Devices** and click **Apply**
- Check **Enable Windows MR** on the *NVRHand* game object
- Test you app! Controllers meshes are downloaded from drivers so they should match the controllers you are using. Physics should work too.

If you have any question ping me on ([twitter](https://twitter.com/meulta))

### CODE REVIEW

**Comment by keithbradner** [comment]
Hi, sorry it's taken me a bit to get to this. Let me start by saying I appreciate that you've tried to fill in all that parts that make this framework easy to use! Adding in the install button I think really does help some people. I know I like it when starting new projects.

There's a couple problems with your pull request that normally I'd fix myself but I'm pretty busy right now. So you can either address them yourself or wait for me to get to them.

Generally we don't support other platforms until it's supported by unity mainline because you have to do a buncha ifdefs to account for people using other versions. Again, if you'd like to add these you're welcome to. This will need to compile if you're targeting standalone as well as wsa.

The minimum version of Unity I'm shooting for right now is 2017.1. Technically right now we support as low as 5.4 but that's getting a bit ridiculous to maintain support for. So I'd need this checkin to at least compile for 2017.1 even though you won't be able to use windows mr with that. There seems to be a few errors for that right now.

Looks like there's also a couple places that don't compile if you don't have the holo toolkit stuff installed. I think you've figured out the ifdefs required for this in other places, just forgot a couple.

I think the NVRWindowsMRIntegration file needs an ifdef around it for if you're using windows mr.

[Optional]
I'd also like it if you linked a prefab of the physical colliders to the different controller types. One of the cool things about NewtonVR is the ability to use your controller as a physical object, and that doesn't work as well if you don't have a good model of the colliders. You should be able to use the example I created for the acer headset for steamvr for most of the controllers, I think they're all pretty similar. This isn't a hard requirement though as to really test this you'd need each controller.

**Comment by etiennemargraff** [comment]
Hello,

**Thanks a lot!** I am going to work on the #ifdefs.

I understand you usually don't support things that are not in the final version of Unity and appreciate that you still consider it. I am working with a lot of devs and it would be easier for me to recommend NewtonVR if the support is in the official repo.

Regarding the prefab for the collider, as WinMR can have a lot of different controllers and controller models, I would prefer sticking to downloading from the drivers (as it's done now). We are using the Acer ones you already have in the project as a fallback if something went wrong with using the one from the drivers. I noticed I have to fix the orientation but it works well. Would it work for you?

I am travelling right now but will work on this asap and let you know!

Thanks

**Comment by etiennemargraff** [comment]
Hey just to let you know that I just came back from holidays and I have been working on an update for the PR.

Should be ready this week!

**Comment by etiennemargraff** [comment]
Updated!

**Comment by keithbradner** [comment]
Just getting over my cold now (oof, nearly 3 weeks!). Is this supposed to work for Unity 2017.3? According to this page it says post 2017.2.1 should work but it just tries to launch steam after I install the holo toolkit package. There doesn't seem to be a windows MR option or whatever in the player settings XR section.

**Comment by keithbradner** [comment]
Whoops nevermind, missed the Apply Mixed Reality Project Settings button. This looks great! And totally does work on 2017.3 (along with the MRTPs). I'm going to go ahead and merge this and then make a couple minor changes. Thanks so much for adding Windows MR support to NewtonVR!

**Comment by schutztj** [comment]
Firstly, thanks for doing this work!  My only comment would be that I would love to see the dependency on MixedRealityToolkit removed.  It appears that the primary reason it's required now is for downloading/rendering the controller models which I think could be re-factored into a much smaller, more manageable dependency for those who don't want to take the complexity and compile-time hit of including the entire MRToolkit.  As a WindowsMR developer, this is definitely something I would need addressed before using NewtonVR on WindowsMR in the future.  If I get some free time, this may be something I'll even try to re-visit.

Thanks again for the work!

**Comment by etiennemargraff** [comment]
@schutztj thank you for your comment on this. Agreed, this is the goal. I will work on this in the coming days !

**Comment by etiennemargraff** [comment]
Well, let me think about that a little bit more. Originally we did it this way because it is the way it works with the other platform. Why do you want it to be included in the case of Mixed reality ? Just so I understand the scenario :)

**Pull request merged**
